# Generated by Django 2.0.2 on 2018-02-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue.UserEntity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
