# Generated by Django 2.0.2 on 2018-02-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ue', '0002_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='MEID',
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.CharField(default=None, help_text='Unit of the measurement, ex. dBm', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='key',
            field=models.CharField(help_text='Key of the measurement, ex. RSRP[0] for RSRP at antenna 0.', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='user_entity',
            field=models.ForeignKey(help_text='User Entity used for measuring.', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='ue.UserEntity'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.CharField(default=None, help_text='Value of the measurement, ex. -100', max_length=100),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='IMEI',
            field=models.CharField(help_text='International Mobile Equipment Identity (IMEI), ex. 35-209900-176148-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='IMSI',
            field=models.CharField(help_text='International mobile subscriber identity (IMSI), ex. 310150123456789', max_length=100),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='name',
            field=models.CharField(help_text='Name of the device, ex. Samsung Galaxy S7', max_length=100),
        ),
    ]
