# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellIdentityLte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.IntegerField()),
                ('mnc', models.IntegerField()),
                ('ci', models.IntegerField()),
                ('pci', models.IntegerField()),
                ('tac', models.IntegerField()),
                ('earfcn', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CellInfoLte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CellSignalStrengthLte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss', models.IntegerField()),
                ('rsrp', models.IntegerField()),
                ('rsrq', models.IntegerField()),
                ('rssnr', models.IntegerField()),
                ('cqi', models.IntegerField()),
                ('ta', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cell_info_lte', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_signal_strength_lte', to='data.CellInfoLte')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='cellidentitylte',
            name='cell_info_lte',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_identity_lte', to='data.CellInfoLte'),
        ),
    ]
