# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20171015_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinfolte',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
