# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171016_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellinfolte',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
